### PR TITLE
Feature 34/create table view/goodman2814

### PR DESCRIPTION
**Pull request by goodman2814**
Created the table on the table page and changed landingPage.html to index.html so that it works with GitHub pages.

### CODE REVIEW

**Review by Emimint — DISMISSED** [review]
I think that at some point, we will need to discuss about how to organize the files and functions it seems ok for now to me 👍 !

**Comment by Emimint** [comment]
@goodman2814 actually, in the case of your branch, it might be better (? not sure) to first merge it locally with the latest changes from the development branch, and then redo the PR.

**Comment by goodman2814** [comment]
> @goodman2814 actually, in the case of your branch, it might be better (? not sure) to first merge it locally with the latest changes from the development branch, and then redo the PR.

It should be able to merge into the development branch as is without having to merge it locally. (I'm also not sure how to do that locally...)

**Review by Emimint — APPROVED** [review]
@goodman2814  in that case, I'm good (maybe try to ask the others indivudually for their reviews as well).

**Review by MrBarker47 — APPROVED** [review]
Looks good!

**Pull request merged**
