### PR TITLE
Finish about page 69 jb

### PR DESCRIPTION
**Pull request by MrBarker47**
Hello team! I finished up the about page and I added a footer to the pages. Let me know if there's anything you want me to change.

### CODE REVIEW

**Comment by Emimint** [comment]
Hey @MrBarker47 ! We can discuss about the About page all together today. As for the footer, I feel like it is a repetition of the nav bar 🤔? Going with the [specs of the project](https://github.com/chingu-voyages/voyage-project-tier1-fireball#general-instructions), the footer should have a link to our teams repo. You can have a look [here ](https://v43-tier1-team-09.netlify.app/)(it is from my previous voyage, and here is the [code ](https://github.com/chingu-voyages/v43-tier1-team-09/blob/main/src/views/renderFooter.js)for the footer).

**Comment by Emimint** [comment]
Hey @MrBarker47 So just a few things:
- The footer is not updated on the tablePage 🤔 :
image
- Could you make it so that the About page is opened in a new tab? You can do that by using the target="_blank" attribute. I feel like it is a shame for the user to completely leave our page :( ...
- Could you try to merge the development branch on your machine first? I am currently trying to incorporate both my changes and the development branch changes in my branch and it is a headache 😢 . If you are having trouble with the conflicts we could look it up together!

**Review by goodman2814 — APPROVED** [review]
Lets merge this and we can add the footer in another update/branch

**Review by Emimint — APPROVED** [review]
> Lets merge this and we can add the footer in another update/branch

@goodman2814 the footer is already ok. The problem is about the conflicts but I guess whoever will merge will handle them!

**Pull request merged**
