### PR TITLE
Send search information to table map and histogram emimint

### PR DESCRIPTION
**Pull request by Emimint**
Hey guys! So the data is reaching the table view just fine :tada: !  
image

So the real issue is with the map for what I understand 🤔 ? If it really does not work, I guess we will go without the map 😢 ...

### CODE REVIEW

**Review by cmade — APPROVED** [review]
Nice work.

**Review by goodman2814 — COMMENTED** [review]
If you swap where the map is initialized, it seems to work

**Review by goodman2814 — APPROVED** [review]
great work!

**Comment by Emimint** [comment]
I fixed the map display so now both the map and the table are showing the current search results 🥳 !

**Pull request merged**
