### PR TITLE
fixed a few bugs on the table page

### PR DESCRIPTION
**Pull request by goodman2814**
The table page layout is no longer stretched out. I removed the link to the main.css file because it was adding styles meant for the landing page. Please use tablePage.css for any style changes on the tablePage.html

I also updated the composition histogram so that it would tell us the number of meteors based on the actual composition label and display the proper names for the compositions when searched.

### CODE REVIEW

**Comment by Emimint** [comment]
Hey @goodman2814 ! I tried it and everything seems to be working fine, only as long as I tried to toggle to the map view: once I do that, and go back to the chart view, the chart is gone.

**Comment by goodman2814** [comment]
> Hey @goodman2814 ! I tried it and everything seems to be working fine, only as long as I tried to toggle to the map view: once I do that, and go back to the chart view, the chart is gone.

Interesting. I'm not having that issue on my end. I'll see if I can find where the problem might be...

**Review by Emimint — APPROVED** [review]
We can see tomorrow where the issue is!

**Comment by Emimint** [comment]
Actually, @goodman2814  I think you just need to add createCombinedChart(data) inside the reset function in searchData.js and it should fix it 👍 !
image

**Review by MrBarker47 — APPROVED** [review]
Good stuff bro!

**Pull request merged**
